# Generated by Django 3.1.6 on 2021-02-07 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateField(auto_created=True, verbose_name='Дата создания заказа')),
                ('status_order', models.CharField(choices=[('Новый', 'Новый'), ('В обработке', 'В обработке'), ('Оплачен', 'Оплачен'), ('Доставлено', 'Доставлено')], default='Новый', max_length=64, verbose_name='Статус заказа')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, verbose_name='Дата создания продукта')),
                ('product_name', models.CharField(max_length=256, verbose_name='Наиминование продукта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('end_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name='Цена со скидкой')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_score', models.DateField(auto_created=True, verbose_name='Дата создания счёта')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='mainapp.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='mainapp.product'),
        ),
    ]
